name: Deploy to DigitalOcean Functions

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # install digitalocean cli
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # install digitalocean serverless plugin
      - name: Install doctl serverless plugin
        run: |
          doctl serverless install

      # get the function namespace id, based on the branch
      #   - main: youtubify-prod-1
      #   - development: youtubify-dev-1
      - name: Get the function namespace id for the current branch
        id: get_namespace_id
        run: |
          if [ $GITHUB_REF = 'refs/heads/main' ]; then
            echo "name=namespace_id=youtubify-prod-1" >> GITHUB_OUTPUT
          elif [ $GITHUB_REF = 'refs/heads/development' ]; then
            echo "name=namespace_id=youtubify-dev-1" >> GITHUB_OUTPUT
          fi

      # connect to the correct serverless namespace, if namespace_id is not empty
      - name: Connect to the correct serverless namespace
        if: steps.get_namespace_id.outputs.namespace_id != ''
        run: |
          doctl serverless connect ${{ steps.get_namespace_id.outputs.namespace_id }}

      # deploy function to digitalocean
      - name: Deploy function
        run: |
          doctl serverless deploy src/
